version: '3.8'

services:
  redis:
    image: redis:8.0-rc1-alpine
    container_name: sun_redis
    ports:
      - "127.0.0.1:6379:6379"
    volumes:
      - ./redis_data:/data
    restart: unless-stopped
    command: redis-server --appendonly yes